### ISSUE TITLE
Doesn't handle 64-bit integers

### ISSUE THREAD

**Issue by DuBistKomisch** [joeferner/node-bplist-parser#12]
Of course JavaScript itself doesn't handle 64-bit integers... but if you have a binary plist from an external source with a 64-bit integer you need to pull out, you're out of luck currently.

I worked around this in a fork here: https://github.com/ViviRnD/node-bplist-parser/commit/9185a502c1c0ee5d04e9424a989e2c086aeb3302, but I doubt this fix would be suitable for everyone. Maybe a better solution is to pick one of the big number libraries as a dependency and return the value as that if it's more than 4 bytes?

**Comment by joeferner** [comment]
I just pushed a possible fix https://github.com/joeferner/node-bplist-parser/commit/490c41864e58c93cffa13c52f658135e0ecf8d1c can you give it a try and if it works for you I'll publish to npm

**Comment by DuBistKomisch** [comment]
Yep, swapped it out in our software and it works as expected. :thumbsup:

**Comment by joeferner** [comment]
published v0.1.1

**Comment by DuBistKomisch** [comment]
Thanks for the quick turnaround!
