### ISSUE TITLE
Incorrect parsing for plist files with empty <string></string> values

### ISSUE THREAD

**Issue by antoinevg** [joeferner/node-bplist-parser#13]
If you have a plist file with an empty `<string></string>` value like this:

```
<plist version="1.0">
    <dict>
        <key>DTPlatformBuild</key>
        <string></string>
        <key>DTPlatformName</key>
        <string>iphonesimulator</string>
        <key>DTPlatformVersion</key>
        <string>10.0</string>
    </dict>
</plist>

```

The parser will ignore it and interpret the next key as the value, giving an output like this:

    {
        "DTPlatformBuild":"DTPlatformName",
        "iphonesimulator":"DTPlatformVersion",
        "10.0": ...
    }

**Comment by ryankask** [comment]
I'm seeing something slightly different. I have

```
...
	<key>LSApplicationCategoryType</key>
	<string></string>
...
```

The parsed value is `null` instead of the an empty string.

**Comment by joeferner** [comment]
Would you mind providing me with a sample binary plist with the above example. I don't have an official way to generate bplists on Linux.

**Comment by antoinevg** [comment]
No problem, I've included both text and binary versions for you: [plist-test-case.zip](https://github.com/joeferner/node-bplist-parser/files/871707/plist-test-case.zip)

Thank you!

**Comment by dnicolson** [comment]
@joeferner, @antoinevg I think this issue can be closed.
